"""Add doctor_consultations table

Revision ID: 11e6d35204c3
Revises: 3324a2476848
Create Date: 2025-09-23 21:31:49.210330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11e6d35204c3'
down_revision = '3324a2476848'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_consultations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('appointment_time', sa.DateTime(), nullable=False, comment='预约的问诊时间'),
    sa.Column('department', sa.String(length=100), nullable=True, comment='科室'),
    sa.Column('status', sa.String(length=20), nullable=True, comment="状态 ('scheduled', 'completed', 'cancelled')"),
    sa.Column('patient_symptoms', sa.Text(), nullable=True, comment='病人主诉的症状'),
    sa.Column('doctor_diagnosis', sa.Text(), nullable=True, comment='医生的诊断和建议'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='记录创建时间'),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doctor_consultations')
    # ### end Alembic commands ###
