"""Initial migration: Create all tables

Revision ID: 3324a2476848
Revises: 
Create Date: 2025-09-22 21:05:02.765563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3324a2476848'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False, comment='用户名，用于登录'),
    sa.Column('password_hash', sa.String(length=256), nullable=False, comment='加密后的密码'),
    sa.Column('role', sa.String(length=10), nullable=False, comment="角色 ('patient', 'doctor')"),
    sa.Column('full_name', sa.String(length=100), nullable=True, comment='真实姓名'),
    sa.Column('age', sa.Integer(), nullable=True, comment='年龄'),
    sa.Column('gender', sa.String(length=10), nullable=True, comment='性别'),
    sa.Column('basic_medical_history', sa.Text(), nullable=True, comment='基础疾病史'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='账户创建时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('ai_consultations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False, comment='关联的病人ID'),
    sa.Column('status', sa.String(length=20), nullable=True, comment="状态 ('in_progress', 'completed', 'pending_review', 'reviewed')"),
    sa.Column('symptom_description', sa.Text(), nullable=True, comment='病人提交的详细症状描述'),
    sa.Column('structured_symptoms', sa.JSON(), nullable=True, comment='结构化的症状信息'),
    sa.Column('ai_diagnosis', sa.String(length=255), nullable=True, comment='AI初步诊断结果'),
    sa.Column('ai_confidence', sa.Float(), nullable=True, comment='AI诊断的匹配度'),
    sa.Column('ai_analysis', sa.Text(), nullable=True, comment='AI给出的详细分析'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='问诊创建时间'),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('doctors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='关联的用户ID'),
    sa.Column('title', sa.String(length=50), nullable=True, comment='职称'),
    sa.Column('specialty', sa.String(length=50), nullable=True, comment='科室/专业'),
    sa.Column('bio', sa.Text(), nullable=True, comment='个人简介/擅长领域'),
    sa.Column('rating', sa.Float(), nullable=True, comment='综合评分'),
    sa.Column('review_count', sa.Integer(), nullable=True, comment='评价数量'),
    sa.Column('available_slots', sa.JSON(), nullable=True, comment='可预约时间段'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False, comment='关联的病人ID'),
    sa.Column('doctor_id', sa.Integer(), nullable=False, comment='关联的医生ID'),
    sa.Column('appointment_time', sa.DateTime(), nullable=False, comment='预约的日期和时间'),
    sa.Column('status', sa.String(length=20), nullable=True, comment="状态 ('scheduled', 'completed', 'canceled')"),
    sa.Column('is_urgent', sa.Boolean(), nullable=True, comment='是否为加急'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='预约创建时间'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consultation_id', sa.Integer(), nullable=False, comment='关联的AI问诊ID'),
    sa.Column('sender_type', sa.String(length=10), nullable=False, comment="发送方 ('user' 或 'ai')"),
    sa.Column('content', sa.Text(), nullable=False, comment='消息内容'),
    sa.Column('timestamp', sa.DateTime(), nullable=True, comment='消息发送时间'),
    sa.ForeignKeyConstraint(['consultation_id'], ['ai_consultations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('doctor_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consultation_id', sa.Integer(), nullable=False, comment='关联的AI问诊ID'),
    sa.Column('doctor_id', sa.Integer(), nullable=False, comment='审核的医生ID'),
    sa.Column('is_approved', sa.Boolean(), nullable=True, comment='审核结果 (True: 确认)'),
    sa.Column('doctor_diagnosis', sa.Text(), nullable=True, comment='医生修改后的诊断'),
    sa.Column('comments', sa.Text(), nullable=True, comment='医生的审核意见'),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True, comment='审核完成的时间'),
    sa.ForeignKeyConstraint(['consultation_id'], ['ai_consultations.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('consultation_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doctor_reviews')
    op.drop_table('chat_messages')
    op.drop_table('appointments')
    op.drop_table('doctors')
    op.drop_table('ai_consultations')
    op.drop_table('users')
    # ### end Alembic commands ###
