"""add_history_to_user

Revision ID: 3adf6ec1a159
Revises: 465c1f484427
Create Date: 2025-10-30 10:42:07.750903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3adf6ec1a159'
down_revision = '465c1f484427'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('personal_history', sa.Text(), nullable=True, comment='个人史 '))
        batch_op.add_column(sa.Column('family_history', sa.Text(), nullable=True, comment='家族史'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('family_history')
        batch_op.drop_column('personal_history')

    # ### end Alembic commands ###
