"""为医生模型添加医院、证号和证书路径字段

Revision ID: 3c7a14d93033
Revises: 11e6d35204c3
Create Date: 2025-09-28 21:23:39.994891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c7a14d93033'
down_revision = '11e6d35204c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hospital', sa.String(length=100), nullable=True, comment='所属医院'))
        batch_op.add_column(sa.Column('license_id', sa.String(length=100), nullable=True, comment='15位执业医师证号'))
        batch_op.add_column(sa.Column('certificate_image_url', sa.String(length=255), nullable=True, comment='资质证明图片路径'))
        batch_op.create_unique_constraint(None, ['license_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('certificate_image_url')
        batch_op.drop_column('license_id')
        batch_op.drop_column('hospital')

    # ### end Alembic commands ###
