"""Add DepartmentModel table

Revision ID: 465c1f484427
Revises: f1e0881daedb
Create Date: 2025-10-27 21:59:30.620611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '465c1f484427'
down_revision = 'f1e0881daedb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='科室名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='科室描述'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('departments')
    # ### end Alembic commands ###
