"""add phone and profile fields to UserModel

Revision ID: 5a50344fcd4e
Revises: f89ffd89cb23
Create Date: 2025-11-02 20:50:16.679642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a50344fcd4e'
down_revision = 'f89ffd89cb23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=11), nullable=True, comment='用户手机号码'))
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=255), nullable=True, comment='头像图片路径'))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True, comment='电子邮箱'))
        batch_op.add_column(sa.Column('id_card', sa.String(length=18), nullable=True, comment='身份证号'))
        batch_op.add_column(sa.Column('insurance_card', sa.String(length=50), nullable=True, comment='医保卡号'))
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.create_unique_constraint(None, ['phone'])
        batch_op.create_unique_constraint(None, ['id_card'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('insurance_card')
        batch_op.drop_column('id_card')
        batch_op.drop_column('email')
        batch_op.drop_column('avatar_url')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
