"""Remove age column and use birth_date instead

Revision ID: 7a248679805e
Revises: 3c7a14d93033
Create Date: 2025-09-28 21:52:42.335685

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7a248679805e'
down_revision = '3c7a14d93033'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birth_date', sa.Date(), nullable=True, comment='出生日期'))
        batch_op.drop_column('age')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', mysql.INTEGER(), autoincrement=False, nullable=True, comment='年龄'))
        batch_op.drop_column('birth_date')

    # ### end Alembic commands ###
