"""Add MedicalRecordModel table

Revision ID: f1e0881daedb
Revises: 7a248679805e
Create Date: 2025-10-27 21:23:05.524313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1e0881daedb'
down_revision = '7a248679805e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False, comment='关联的病人ID'),
    sa.Column('chief_complaint', sa.Text(), nullable=True, comment='主诉'),
    sa.Column('history_present_illness', sa.Text(), nullable=True, comment='现病史'),
    sa.Column('past_medical_history', sa.Text(), nullable=True, comment='既往史'),
    sa.Column('personal_history', sa.Text(), nullable=True, comment='个人史'),
    sa.Column('family_history', sa.Text(), nullable=True, comment='家族史'),
    sa.Column('diagnosis', sa.Text(), nullable=True, comment='诊断结果'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='病历创建时间'),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medical_records')
    # ### end Alembic commands ###
