"""add_medical_record_id_to_appointments

Revision ID: f89ffd89cb23
Revises: 3adf6ec1a159
Create Date: 2025-11-01 20:50:12.047042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f89ffd89cb23'
down_revision = '3adf6ec1a159'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('medical_record_id', sa.Integer(), nullable=True, comment='关联的AI病历ID'))
        batch_op.create_foreign_key(None, 'medical_records', ['medical_record_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('medical_record_id')

    # ### end Alembic commands ###
